# Docker Build
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '3000a247-b2aa-4e4a-82e9-8688597064ef'
  imageRepository: 'sliemresumebuilder'
  containerRegistry: 'builderproj.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Azure_Pipeline/Dockerfile'
  tag: 'latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: new-agent-pool
    steps:
    - script: |
        cd $(Build.SourcesDirectory)/Azure_Pipeline
        cat Dockerfile
        docker build -t $(containerRegistry)/$(imageRepository):$(tag) -f $(dockerfilePath) .
        docker push $(containerRegistry)/$(imageRepository):$(tag)
      displayName: 'Build and push an image to Azure Container Registry'
# docker run -e API_KEY=$(API_KEY) $(containerRegistry)/$(imageRepository):$(tag)