# Docker
# Build and push image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'add7ab35-4a33-4d0a-b81f-3f5926bf28d7'
  imageRepository: 'sliemresumebuilder'
  containerRegistry: 'builderproj.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/AWS_ECS/Dockerfile'  # Corrected path with straight quotation marks
  tag: '$(Build.BuildId)'
  imagePullSecret: 'builderproj203657ba-auth'

stages:
- stage: BuildAndPush
  displayName: Build and push stage
  jobs:
  - job: BuildAndPush
    displayName: Build and push
    pool:
      name: new-agent-pool
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests
